name: Build Debian images

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 23 * * *'

env:
  IMAGE_TAG: master

jobs:
  build-and-push-debian-images:
    strategy:
      matrix:
        include:
        - image-id: debian-11-pdns-base
          debian-release-name: bullseye-slim
        - image-id: debian-bookworm-pdns-base
          debian-release-name: bookworm-slim
    env:
      IMAGE_ID: ghcr.io/${{ github.repository }}/debian-11-pdns-base
      DEBIAN_RELEASE_NAME: bullseye-slim
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: |
          docker build . --file Dockerfile \
            --tag ghcr.io/${{ github.repository }}/${{ matrix.image-id }}:${{ env.IMAGE_TAG }} \
            --build-arg DEBIAN_IMAGE_TAG=${{ matrix.debian-release-name }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push into Github Container Registry
        run: |
          docker push ghcr.io/${{ github.repository }}/${{ matrix.image-id }}:${{ env.IMAGE_TAG }}
