name: Build Docker Debian Bookworm image

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '30 23 * * *'

env:
  IMAGE_ID: ghcr.io/romeroalx/base-pdns-ci-image/debian-bookworm-pdns-base
  IMAGE_TAG: "master"
  DEBIAN_RELEASE_NAME: "bookworm-slim"

jobs:
  build-and-push-debian-image:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: |
          docker build . --file Dockerfile --tag $IMAGE_ID:$IMAGE_TAG \
            --build-arg IMAGE_TAG=$DEBIAN_RELEASE_NAME

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push into Github Container Registry
        run: |
          docker push $IMAGE_ID:$IMAGE_TAG
