name: Build Debian images

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 23 * * *'

jobs:
  build-and-push-debian-bullseye-image:
    env:
      IMAGE_ID: ghcr.io/${{ github.repository }}/debian-11-pdns-base
      IMAGE_TAG: master
      DEBIAN_RELEASE_NAME: bullseye-slim
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: |
          docker build . --file Dockerfile --tag $IMAGE_ID:$IMAGE_TAG \
            --build-arg DEBIAN_IMAGE_TAG=$DEBIAN_RELEASE_NAME

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push into Github Container Registry
        run: |
          docker push $IMAGE_ID:$IMAGE_TAG

  build-and-push-debian-bookworm-image:
    env:
      IMAGE_ID: ghcr.io/${{ github.repository }}/debian-bookworm-pdns-base
      IMAGE_TAG: master
      DEBIAN_RELEASE_NAME: bookworm-slim
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: |
          docker build . --file Dockerfile --tag $IMAGE_ID:$IMAGE_TAG \
            --build-arg DEBIAN_IMAGE_TAG=$DEBIAN_RELEASE_NAME

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push into Github Container Registry
        run: |
          docker push $IMAGE_ID:$IMAGE_TAG
